# Generated by Django 6.0.3 on 2026-03-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('CABELO', 'Produtos para Cabelo'), ('TINTAS', 'Tintas e Colorações'), ('UNHAS', 'Produtos para Unhas'), ('MAQUIAGEM', 'Maquiagem'), ('SPA', 'Spa e Tratamentos'), ('DEPILACAO', 'Depilação'), ('SOBRANCELHAS', 'Sobrancelhas e Cílios')], default='CABELO', max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
