# Generated by Django 6.0.3 on 2026-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_remove_agendamento_restored_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
