# Generated by Django 6.0.3 on 2026-03-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_remove_agendamento_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
