# Generated by Django 6.0.3 on 2026-03-20 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_remove_profissional_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
