# Generated by Django 6.0.3 on 2026-03-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='categoria',
            field=models.CharField(choices=[('CABELO', 'Cabelo'), ('MAQUIAGEM', 'Maquiagem'), ('SPA', 'Spa'), ('UNHAS', 'Unhas'), ('BARBA', 'Barba'), ('DEPILACAO', 'Depilação'), ('MASSAGEM', 'Massagem')], default='CABELO', max_length=20),
        ),
    ]
