# Generated by Django 6.0.3 on 2026-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_servico_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.CharField(choices=[('CABELO', 'Cabelo'), ('MAQUIAGEM', 'Maquiagem'), ('SPA', 'Spa'), ('UNHAS', 'Unhas'), ('BARBA', 'Barba'), ('DEPILACAO', 'Depilação'), ('MASSAGEM', 'Massagem'), ('SOBRANCELHAS', 'Sobrancelhas'), ('CILIOS', 'Cílios')], default='CABELO', max_length=20),
        ),
    ]
