# Generated by Django 6.0.3 on 2026-03-17 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_servico_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='servico',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servico',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
